plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.atmbank'
version = '1.0.0'

java {
    targetCompatibility = JavaVersion.VERSION_16
    sourceCompatibility = JavaVersion.VERSION_16
}

application {
    mainClass = 'com.atmbank.atm.Main'
}

jar {
    manifest {
        attributes['Main-Class'] = application.mainClass
    }
}

shadowJar {
    manifest {
        attributes['Main-Class'] = application.mainClass
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'commons-cli:commons-cli:1.9.0'
    implementation project(':common')
}
