plugins {
    id 'java-library'
}

group = 'com.atmbank'
version = '1.0.0'

java {
    targetCompatibility = JavaVersion.VERSION_16
    sourceCompatibility = JavaVersion.VERSION_16
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'commons-codec:commons-codec:1.18.0'
}
